DTL\Bundle\ContentBundle\Document\HomepageDocument:
    uri_schema: "/"
    conflict_resolver: throw_exception

DTL\Bundle\ContentBundle\Document\PageDocument:
    uri_schema: "{url}/{title}"
    token_providers:
        url: [content_method, { method: getResourceLocator, slugify: false  }]
        title: [content_method, { method: getTitle }]
    conflict_resolver: auto_increment
